// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/paxos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	SenderId      int32                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	InstanceId    int32                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_proto_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *PrepareRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PrepareRequest) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type PromiseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promised      bool                   `protobuf:"varint,1,opt,name=promised,proto3" json:"promised,omitempty"`
	AcceptedId    int64                  `protobuf:"varint,2,opt,name=accepted_id,json=acceptedId,proto3" json:"accepted_id,omitempty"`
	AcceptedValue []byte                 `protobuf:"bytes,3,opt,name=accepted_value,json=acceptedValue,proto3" json:"accepted_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseResponse) Reset() {
	*x = PromiseResponse{}
	mi := &file_proto_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseResponse) ProtoMessage() {}

func (x *PromiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseResponse.ProtoReflect.Descriptor instead.
func (*PromiseResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *PromiseResponse) GetPromised() bool {
	if x != nil {
		return x.Promised
	}
	return false
}

func (x *PromiseResponse) GetAcceptedId() int64 {
	if x != nil {
		return x.AcceptedId
	}
	return 0
}

func (x *PromiseResponse) GetAcceptedValue() []byte {
	if x != nil {
		return x.AcceptedValue
	}
	return nil
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	SenderId      int32                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	InstanceId    int32                  `protobuf:"varint,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_proto_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *AcceptRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AcceptRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *AcceptRequest) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type AcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedResponse) Reset() {
	*x = AcceptedResponse{}
	mi := &file_proto_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedResponse) ProtoMessage() {}

func (x *AcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedResponse.ProtoReflect.Descriptor instead.
func (*AcceptedResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptedResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	SenderId      int32                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	InstanceId    int32                  `protobuf:"varint,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *CommitRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *CommitRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CommitRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CommitRequest) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        bool                   `protobuf:"varint,1,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *CommitResponse) GetCommit() bool {
	if x != nil {
		return x.Commit
	}
	return false
}

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_proto_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *GetLogRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type GetLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextIndex     int32                  `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,2,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogResponse) Reset() {
	*x = GetLogResponse{}
	mi := &file_proto_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogResponse) ProtoMessage() {}

func (x *GetLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogResponse.ProtoReflect.Descriptor instead.
func (*GetLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *GetLogResponse) GetNextIndex() int32 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *GetLogResponse) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int32                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *LogEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_proto_rawDesc = "" +
	"\n" +
	"\x11proto/paxos.proto\x12\x05paxos\"o\n" +
	"\x0ePrepareRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x05R\n" +
	"instanceId\"u\n" +
	"\x0fPromiseResponse\x12\x1a\n" +
	"\bpromised\x18\x01 \x01(\bR\bpromised\x12\x1f\n" +
	"\vaccepted_id\x18\x02 \x01(\x03R\n" +
	"acceptedId\x12%\n" +
	"\x0eaccepted_value\x18\x03 \x01(\fR\racceptedValue\"\x84\x01\n" +
	"\rAcceptRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\x05R\n" +
	"instanceId\".\n" +
	"\x10AcceptedResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x84\x01\n" +
	"\rCommitRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\x05R\n" +
	"instanceId\"(\n" +
	"\x0eCommitResponse\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\bR\x06commit\",\n" +
	"\rGetLogRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\"a\n" +
	"\x0eGetLogResponse\x12\x1d\n" +
	"\n" +
	"next_index\x18\x01 \x01(\x05R\tnextIndex\x120\n" +
	"\vlog_entries\x18\x02 \x03(\v2\x0f.paxos.LogEntryR\n" +
	"logEntries\"A\n" +
	"\bLogEntry\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x05R\n" +
	"instanceId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2\xed\x01\n" +
	"\x05Paxos\x128\n" +
	"\aPrepare\x12\x15.paxos.PrepareRequest\x1a\x16.paxos.PromiseResponse\x127\n" +
	"\x06Accept\x12\x14.paxos.AcceptRequest\x1a\x17.paxos.AcceptedResponse\x125\n" +
	"\x06Commit\x12\x14.paxos.CommitRequest\x1a\x15.paxos.CommitResponse\x12:\n" +
	"\vGetLogState\x12\x14.paxos.GetLogRequest\x1a\x15.paxos.GetLogResponseB\x13Z\x11paxos/proto;protob\x06proto3"

var (
	file_proto_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_proto_rawDescData []byte
)

func file_proto_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_proto_rawDescData
}

var file_proto_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_paxos_proto_goTypes = []any{
	(*PrepareRequest)(nil),   // 0: paxos.PrepareRequest
	(*PromiseResponse)(nil),  // 1: paxos.PromiseResponse
	(*AcceptRequest)(nil),    // 2: paxos.AcceptRequest
	(*AcceptedResponse)(nil), // 3: paxos.AcceptedResponse
	(*CommitRequest)(nil),    // 4: paxos.CommitRequest
	(*CommitResponse)(nil),   // 5: paxos.CommitResponse
	(*GetLogRequest)(nil),    // 6: paxos.GetLogRequest
	(*GetLogResponse)(nil),   // 7: paxos.GetLogResponse
	(*LogEntry)(nil),         // 8: paxos.LogEntry
}
var file_proto_paxos_proto_depIdxs = []int32{
	8, // 0: paxos.GetLogResponse.log_entries:type_name -> paxos.LogEntry
	0, // 1: paxos.Paxos.Prepare:input_type -> paxos.PrepareRequest
	2, // 2: paxos.Paxos.Accept:input_type -> paxos.AcceptRequest
	4, // 3: paxos.Paxos.Commit:input_type -> paxos.CommitRequest
	6, // 4: paxos.Paxos.GetLogState:input_type -> paxos.GetLogRequest
	1, // 5: paxos.Paxos.Prepare:output_type -> paxos.PromiseResponse
	3, // 6: paxos.Paxos.Accept:output_type -> paxos.AcceptedResponse
	5, // 7: paxos.Paxos.Commit:output_type -> paxos.CommitResponse
	7, // 8: paxos.Paxos.GetLogState:output_type -> paxos.GetLogResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_paxos_proto_init() }
func file_proto_paxos_proto_init() {
	if File_proto_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_proto_depIdxs,
		MessageInfos:      file_proto_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_proto = out.File
	file_proto_paxos_proto_goTypes = nil
	file_proto_paxos_proto_depIdxs = nil
}
